<?php

namespace App\Traits;


trait IconList
{
    function font_awesome($type = "all")
    {
        $fa = [];

        $brands = ["fa-500px", "fa-accessible-icon", "fa-accusoft", "fa-acquisitions-incorporated", "fa-adn", "fa-adobe", "fa-adversal", "fa-affiliatetheme", "fa-airbnb", "fa-algolia", "fa-alipay", "fa-amazon", "fa-amazon-pay", "fa-amilia", "fa-android", "fa-angellist", "fa-angrycreative", "fa-angular", "fa-app-store", "fa-app-store-ios", "fa-apper", "fa-apple", "fa-apple-pay", "fa-artstation", "fa-asymmetrik", "fa-atlassian", "fa-audible", "fa-autoprefixer", "fa-avianex", "fa-aviato", "fa-aws", "fa-bandcamp", "fa-battle-net", "fa-behance", "fa-behance-square", "fa-bimobject", "fa-bitbucket", "fa-bitcoin", "fa-bity", "fa-black-tie", "fa-blackberry", "fa-blogger", "fa-blogger-b", "fa-bluetooth", "fa-bluetooth-b", "fa-bootstrap", "fa-btc", "fa-buffer", "fa-buromobelexperte", "fa-buy-n-large", "fa-buysellads", "fa-canadian-maple-leaf", "fa-cc-amazon-pay", "fa-cc-amex", "fa-cc-apple-pay", "fa-cc-diners-club", "fa-cc-discover", "fa-cc-jcb", "fa-cc-mastercard", "fa-cc-paypal", "fa-cc-stripe", "fa-cc-visa", "fa-centercode", "fa-centos", "fa-chrome", "fa-chromecast", "fa-cloudscale", "fa-cloudsmith", "fa-cloudversify", "fa-codepen", "fa-codiepie", "fa-confluence", "fa-connectdevelop", "fa-contao", "fa-cotton-bureau", "fa-cpanel", "fa-creative-commons", "fa-creative-commons-by", "fa-creative-commons-nc", "fa-creative-commons-nc-eu", "fa-creative-commons-nc-jp", "fa-creative-commons-nd", "fa-creative-commons-pd", "fa-creative-commons-pd-alt", "fa-creative-commons-remix", "fa-creative-commons-sa", "fa-creative-commons-sampling", "fa-creative-commons-sampling-plus", "fa-creative-commons-share", "fa-creative-commons-zero", "fa-critical-role", "fa-css3", "fa-css3-alt", "fa-cuttlefish", "fa-d-and-d", "fa-d-and-d-beyond", "fa-dashcube", "fa-delicious", "fa-deploydog", "fa-deskpro", "fa-dev", "fa-deviantart", "fa-dhl", "fa-diaspora", "fa-digg", "fa-digital-ocean", "fa-discord", "fa-discourse", "fa-dochub", "fa-docker", "fa-draft2digital", "fa-dribbble", "fa-dribbble-square", "fa-dropbox", "fa-drupal", "fa-dyalog", "fa-earlybirds", "fa-ebay", "fa-edge", "fa-elementor", "fa-ello", "fa-ember", "fa-empire", "fa-envira", "fa-erlang", "fa-ethereum", "fa-etsy", "fa-evernote", "fa-expeditedssl", "fa-facebook", "fa-facebook-f", "fa-facebook-messenger", "fa-facebook-square", "fa-fantasy-flight-games", "fa-fedex", "fa-fedora", "fa-figma", "fa-firefox", "fa-firefox-browser", "fa-first-order", "fa-first-order-alt", "fa-firstdraft", "fa-flickr", "fa-flipboard", "fa-fly", "fa-font-awesome", "fa-font-awesome-alt", "fa-font-awesome-flag", "fa-fonticons", "fa-fonticons-fi", "fa-fort-awesome", "fa-fort-awesome-alt", "fa-forumbee", "fa-foursquare", "fa-free-code-camp", "fa-freebsd", "fa-fulcrum", "fa-galactic-republic", "fa-galactic-senate", "fa-get-pocket", "fa-gg", "fa-gg-circle", "fa-git", "fa-git-alt", "fa-git-square", "fa-github", "fa-github-alt", "fa-github-square", "fa-gitkraken", "fa-gitlab", "fa-gitter", "fa-glide", "fa-glide-g", "fa-gofore", "fa-goodreads", "fa-goodreads-g", "fa-google", "fa-google-drive", "fa-google-play", "fa-google-plus", "fa-google-plus-g", "fa-google-plus-square", "fa-google-wallet", "fa-gratipay", "fa-grav", "fa-gripfire", "fa-grunt", "fa-gulp", "fa-hacker-news", "fa-hacker-news-square", "fa-hackerrank", "fa-hips", "fa-hire-a-helper", "fa-hooli", "fa-hornbill", "fa-hotjar", "fa-houzz", "fa-html5", "fa-hubspot", "fa-ideal", "fa-imdb", "fa-instagram", "fa-intercom", "fa-internet-explorer", "fa-invision", "fa-ioxhost", "fa-itch-io", "fa-itunes", "fa-itunes-note", "fa-java", "fa-jedi-order", "fa-jenkins", "fa-jira", "fa-joget", "fa-joomla", "fa-js", "fa-js-square", "fa-jsfiddle", "fa-kaggle", "fa-keybase", "fa-keycdn", "fa-kickstarter", "fa-kickstarter-k", "fa-korvue", "fa-laravel", "fa-lastfm", "fa-lastfm-square", "fa-leanpub", "fa-less", "fa-line", "fa-linkedin", "fa-linkedin-in", "fa-linode", "fa-linux", "fa-lyft", "fa-magento", "fa-mailchimp", "fa-mandalorian", "fa-markdown", "fa-mastodon", "fa-maxcdn", "fa-mdb", "fa-medapps", "fa-medium", "fa-medium-m", "fa-medrt", "fa-meetup", "fa-megaport", "fa-mendeley", "fa-microblog", "fa-microsoft", "fa-mix", "fa-mixcloud", "fa-mizuni", "fa-modx", "fa-monero", "fa-napster", "fa-neos", "fa-nimblr", "fa-node", "fa-node-js", "fa-npm", "fa-ns8", "fa-nutritionix", "fa-odnoklassniki", "fa-odnoklassniki-square", "fa-old-republic", "fa-opencart", "fa-openid", "fa-opera", "fa-optin-monster", "fa-orcid", "fa-osi", "fa-page4", "fa-pagelines", "fa-palfed", "fa-patreon", "fa-paypal", "fa-penny-arcade", "fa-periscope", "fa-phabricator", "fa-phoenix-framework", "fa-phoenix-squadron", "fa-php", "fa-pied-piper", "fa-pied-piper-alt", "fa-pied-piper-hat", "fa-pied-piper-pp", "fa-pied-piper-square", "fa-pinterest", "fa-pinterest-p", "fa-pinterest-square", "fa-playstation", "fa-product-hunt", "fa-pushed", "fa-python", "fa-qq", "fa-quinscape", "fa-quora", "fa-r-project", "fa-raspberry-pi", "fa-ravelry", "fa-react", "fa-reacteurope", "fa-readme", "fa-rebel", "fa-red-river", "fa-reddit", "fa-reddit-alien", "fa-reddit-square", "fa-redhat", "fa-renren", "fa-replyd", "fa-researchgate", "fa-resolving", "fa-rev", "fa-rocketchat", "fa-rockrms", "fa-safari", "fa-salesforce", "fa-sass", "fa-schlix", "fa-scribd", "fa-searchengin", "fa-sellcast", "fa-sellsy", "fa-servicestack", "fa-shirtsinbulk", "fa-shopware", "fa-simplybuilt", "fa-sistrix", "fa-sith", "fa-sketch", "fa-skyatlas", "fa-skype", "fa-slack", "fa-slack-hash", "fa-slideshare", "fa-snapchat", "fa-snapchat-ghost", "fa-snapchat-square", "fa-soundcloud", "fa-sourcetree", "fa-speakap", "fa-speaker-deck", "fa-spotify", "fa-squarespace", "fa-stack-exchange", "fa-stack-overflow", "fa-stackpath", "fa-staylinked", "fa-steam", "fa-steam-square", "fa-steam-symbol", "fa-sticker-mule", "fa-strava", "fa-stripe", "fa-stripe-s", "fa-studiovinari", "fa-stumbleupon", "fa-stumbleupon-circle", "fa-superpowers", "fa-supple", "fa-suse", "fa-swift", "fa-symfony", "fa-teamspeak", "fa-telegram", "fa-telegram-plane", "fa-tencent-weibo", "fa-the-red-yeti", "fa-themeco", "fa-themeisle", "fa-think-peaks", "fa-trade-federation", "fa-trello", "fa-tripadvisor", "fa-tumblr", "fa-tumblr-square", "fa-twitch", "fa-twitter", "fa-twitter-square", "fa-typo3", "fa-uber", "fa-ubuntu", "fa-uikit", "fa-umbraco", "fa-uniregistry", "fa-unity", "fa-untappd", "fa-ups", "fa-usb", "fa-usps", "fa-ussunnah", "fa-vaadin", "fa-viacoin", "fa-viadeo", "fa-viadeo-square", "fa-viber", "fa-vimeo", "fa-vimeo-square", "fa-vimeo-v", "fa-vine", "fa-vk", "fa-vnv", "fa-vuejs", "fa-waze", "fa-weebly", "fa-weibo", "fa-weixin", "fa-whatsapp", "fa-whatsapp-square", "fa-whmcs", "fa-wikipedia-w", "fa-windows", "fa-wix", "fa-wizards-of-the-coast", "fa-wolf-pack-battalion", "fa-wordpress", "fa-wordpress-simple", "fa-wpbeginner", "fa-wpexplorer", "fa-wpforms", "fa-wpressr", "fa-xbox", "fa-xing", "fa-xing-square", "fa-y-combinator", "fa-yahoo", "fa-yammer", "fa-yandex", "fa-yandex-international", "fa-yarn", "fa-yelp", "fa-yoast", "fa-youtube", "fa-youtube-square", "fa-zhihu"];
        $icons = ["fa-abacus", "fa-acorn", "fa-ad", "fa-address-book", "fa-address-card", "fa-adjust", "fa-air-conditioner", "fa-air-freshener", "fa-alarm-clock", "fa-alarm-exclamation", "fa-alarm-plus", "fa-alarm-snooze", "fa-album", "fa-album-collection", "fa-alicorn", "fa-alien", "fa-alien-monster", "fa-align-center", "fa-align-justify", "fa-align-left", "fa-align-right", "fa-align-slash", "fa-allergies", "fa-ambulance", "fa-american-sign-language-interpreting", "fa-amp-guitar", "fa-analytics", "fa-anchor", "fa-angel", "fa-angle-double-down", "fa-angle-double-left", "fa-angle-double-right", "fa-angle-double-up", "fa-angle-down", "fa-angle-left", "fa-angle-right", "fa-angle-up", "fa-angry", "fa-ankh", "fa-apple-alt", "fa-apple-crate", "fa-archive", "fa-archway", "fa-arrow-alt-circle-down", "fa-arrow-alt-circle-left", "fa-arrow-alt-circle-right", "fa-arrow-alt-circle-up", "fa-arrow-alt-down", "fa-arrow-alt-from-bottom", "fa-arrow-alt-from-left", "fa-arrow-alt-from-right", "fa-arrow-alt-from-top", "fa-arrow-alt-left", "fa-arrow-alt-right", "fa-arrow-alt-square-down", "fa-arrow-alt-square-left", "fa-arrow-alt-square-right", "fa-arrow-alt-square-up", "fa-arrow-alt-to-bottom", "fa-arrow-alt-to-left", "fa-arrow-alt-to-right", "fa-arrow-alt-to-top", "fa-arrow-alt-up", "fa-arrow-circle-down", "fa-arrow-circle-left", "fa-arrow-circle-right", "fa-arrow-circle-up", "fa-arrow-down", "fa-arrow-from-bottom", "fa-arrow-from-left", "fa-arrow-from-right", "fa-arrow-from-top", "fa-arrow-left", "fa-arrow-right", "fa-arrow-square-down", "fa-arrow-square-left", "fa-arrow-square-right", "fa-arrow-square-up", "fa-arrow-to-bottom", "fa-arrow-to-left", "fa-arrow-to-right", "fa-arrow-to-top", "fa-arrow-up", "fa-arrows", "fa-arrows-alt", "fa-arrows-alt-h", "fa-arrows-alt-v", "fa-arrows-h", "fa-arrows-v", "fa-assistive-listening-systems", "fa-asterisk", "fa-at", "fa-atlas", "fa-atom", "fa-atom-alt", "fa-audio-description", "fa-award", "fa-axe", "fa-axe-battle", "fa-baby", "fa-baby-carriage", "fa-backpack", "fa-backspace", "fa-backward", "fa-bacon", "fa-badge", "fa-badge-check", "fa-badge-dollar", "fa-badge-percent", "fa-badge-sheriff", "fa-badger-honey", "fa-bags-shopping", "fa-bahai", "fa-balance-scale", "fa-balance-scale-left", "fa-balance-scale-right", "fa-ball-pile", "fa-ballot", "fa-ballot-check", "fa-ban", "fa-band-aid", "fa-banjo", "fa-barcode", "fa-barcode-alt", "fa-barcode-read", "fa-barcode-scan", "fa-bars", "fa-baseball", "fa-baseball-ball", "fa-basketball-ball", "fa-basketball-hoop", "fa-bat", "fa-bath", "fa-battery-bolt", "fa-battery-empty", "fa-battery-full", "fa-battery-half", "fa-battery-quarter", "fa-battery-slash", "fa-battery-three-quarters", "fa-bed", "fa-bed-alt", "fa-bed-bunk", "fa-bed-empty", "fa-beer", "fa-bell", "fa-bell-exclamation", "fa-bell-on", "fa-bell-plus", "fa-bell-school", "fa-bell-school-slash", "fa-bell-slash", "fa-bells", "fa-betamax", "fa-bezier-curve", "fa-bible", "fa-bicycle", "fa-biking", "fa-biking-mountain", "fa-binoculars", "fa-biohazard", "fa-birthday-cake", "fa-blanket", "fa-blender", "fa-blender-phone", "fa-blind", "fa-blinds", "fa-blinds-open", "fa-blinds-raised", "fa-blog", "fa-bold", "fa-bolt", "fa-bomb", "fa-bone", "fa-bone-break", "fa-bong", "fa-book", "fa-book-alt", "fa-book-dead", "fa-book-heart", "fa-book-medical", "fa-book-open", "fa-book-reader", "fa-book-spells", "fa-book-user", "fa-bookmark", "fa-books", "fa-books-medical", "fa-boombox", "fa-boot", "fa-booth-curtain", "fa-border-all", "fa-border-bottom", "fa-border-center-h", "fa-border-center-v", "fa-border-inner", "fa-border-left", "fa-border-none", "fa-border-outer", "fa-border-right", "fa-border-style", "fa-border-style-alt", "fa-border-top", "fa-bow-arrow", "fa-bowling-ball", "fa-bowling-pins", "fa-box", "fa-box-alt", "fa-box-ballot", "fa-box-check", "fa-box-fragile", "fa-box-full", "fa-box-heart", "fa-box-open", "fa-box-up", "fa-box-usd", "fa-boxes", "fa-boxes-alt", "fa-boxing-glove", "fa-brackets", "fa-brackets-curly", "fa-braille", "fa-brain", "fa-bread-loaf", "fa-bread-slice", "fa-briefcase", "fa-briefcase-medical", "fa-bring-forward", "fa-bring-front", "fa-broadcast-tower", "fa-broom", "fa-browser", "fa-brush", "fa-bug", "fa-building", "fa-bullhorn", "fa-bullseye", "fa-bullseye-arrow", "fa-bullseye-pointer", "fa-burger-soda", "fa-burn", "fa-burrito", "fa-bus", "fa-bus-alt", "fa-bus-school", "fa-business-time", "fa-cabinet-filing", "fa-cactus", "fa-calculator", "fa-calculator-alt", "fa-calendar", "fa-calendar-alt", "fa-calendar-check", "fa-calendar-day", "fa-calendar-edit", "fa-calendar-exclamation", "fa-calendar-minus", "fa-calendar-plus", "fa-calendar-star", "fa-calendar-times", "fa-calendar-week", "fa-camcorder", "fa-camera", "fa-camera-alt", "fa-camera-home", "fa-camera-movie", "fa-camera-polaroid", "fa-camera-retro", "fa-campfire", "fa-campground", "fa-candle-holder", "fa-candy-cane", "fa-candy-corn", "fa-cannabis", "fa-capsules", "fa-car", "fa-car-alt", "fa-car-battery", "fa-car-building", "fa-car-bump", "fa-car-bus", "fa-car-crash", "fa-car-garage", "fa-car-mechanic", "fa-car-side", "fa-car-tilt", "fa-car-wash", "fa-caravan", "fa-caravan-alt", "fa-caret-circle-down", "fa-caret-circle-left", "fa-caret-circle-right", "fa-caret-circle-up", "fa-caret-down", "fa-caret-left", "fa-caret-right", "fa-caret-square-down", "fa-car"];

        switch ($type) {


            case "brands":
            {
                foreach ($brands as $brand) {
                    $fa["fab " . $brand] = "fab " . $brand;
                }
                break;
            }
            default:
            {
                foreach ($brands as $brand) {
                    $fa["fab " . $brand] = "fab " . $brand;
                }
                foreach ($icons as $icon) {
                    $fa["fab " . $icon] = "fab " . $icon;
                }
                break;
            }
        }

        return $fa;
    }


    function themify($type)
    {
        switch ($type) {
            case 'arrows':
                return [
                    'ti-arrow-up' => 'arrow-up',
                    'ti-arrow-right' => 'arrow-right',
                    'ti-arrow-left' => 'arrow-left',
                    'ti-arrow-down' => 'arrow-down',
                    'ti-arrows-vertical' => 'arrows-vertical',
                    'ti-arrows-horizontal' => 'arrows-horizontal',
                    'ti-angle-up' => 'angle-up',
                    'ti-angle-right' => 'angle-right',
                    'ti-angle-left' => 'angle-left',
                    'ti-angle-down' => 'angle-down',
                    'ti-angle-double-up' => 'angle-double-up',
                    'ti-angle-double-right' => 'angle-double-right',
                    'ti-angle-double-left' => 'angle-double-left',
                    'ti-angle-double-down' => 'angle-double-down',
                    'ti-move' => 'move',
                    'ti-fullscreen' => 'fullscreen',
                    'ti-arrow-top-right' => 'arrow-top-right',
                    'ti-arrow-top-left' => 'arrow-top-left',
                    'ti-arrow-circle-up' => 'arrow-circle-up',
                    'ti-arrow-circle-right' => 'arrow-circle-right',
                    'ti-arrow-circle-left' => 'arrow-circle-left',
                    'ti-arrow-circle-down' => 'arrow-circle-down',
                    'ti-arrows-corner' => 'arrows-corner',
                    'ti-split-v' => 'split-v',
                    'ti-split-v-alt' => 'split-v-alt',
                    'ti-split-h' => 'split-h',
                    'ti-hand-point-up' => 'hand-point-up',
                    'ti-hand-point-right' => 'hand-point-right',
                    'ti-hand-point-left' => 'hand-point-left',
                    'ti-hand-point-down' => 'hand-point-down',
                    'ti-back-right' => 'back-right',
                    'ti-back-left' => 'back-left',
                    'ti-exchange-vertical' => 'exchange-vertical'
                ];
            case 'web':
                return [
                    'ti-wand' => 'wand',
                    'ti-save' => 'save',
                    'ti-save-alt' => 'save-alt',
                    'ti-direction' => 'direction',
                    'ti-direction-alt' => 'direction-alt',
                    'ti-user' => 'user',
                    'ti-link' => 'link',
                    'ti-unlink' => 'unlink',
                    'ti-trash' => 'trash',
                    'ti-target' => 'target',
                    'ti-tag' => 'tag',
                    'ti-desktop' => 'desktop',
                    'ti-tablet' => 'tablet',
                    'ti-mobile' => 'mobile',
                    'ti-email' => 'email',
                    'ti-star' => 'star',
                    'ti-spray' => 'spray',
                    'ti-signal' => 'signal',
                    'ti-shopping-cart' => 'shopping-cart',
                    'ti-shopping-cart-full' => 'shopping-cart-full',
                    'ti-settings' => 'settings',
                    'ti-search' => 'search',
                    'ti-zoom-in' => 'zoom-in',
                    'ti-zoom-out' => 'zoom-out',
                    'ti-cut' => 'cut',
                    'ti-ruler' => 'ruler',
                    'ti-ruler-alt-2' => 'ruler-alt-2',
                    'ti-ruler-pencil' => 'ruler-pencil',
                    'ti-ruler-alt' => 'ruler-alt',
                    'ti-bookmark' => 'bookmark',
                    'ti-bookmark-alt' => 'bookmark-alt',
                    'ti-reload' => 'reload',
                    'ti-plus' => 'plus',
                    'ti-minus' => 'minus',
                    'ti-close' => 'close',
                    'ti-pin' => 'pin',
                    'ti-pencil' => 'pencil',
                    'ti-pencil-alt' => 'pencil-alt',
                    'ti-paint-roller' => 'paint-roller',
                    'ti-paint-bucket' => 'paint-bucket',
                    'ti-na' => 'na',
                    'ti-medall' => 'medall',
                    'ti-medall-alt' => 'medall-alt',
                    'ti-marker' => 'marker',
                    'ti-marker-alt' => 'marker-alt',
                    'ti-lock' => 'lock',
                    'ti-unlock' => 'unlock',
                    'ti-location-arrow' => 'location-arrow',
                    'ti-layout' => 'layout',
                    'ti-layers' => 'layers',
                    'ti-layers-alt' => 'layers-alt',
                    'ti-key' => 'key',
                    'ti-image' => 'image',
                    'ti-heart' => 'heart',
                    'ti-heart-broken' => 'heart-broken',
                    'ti-hand-stop' => 'hand-stop',
                    'ti-hand-open' => 'hand-open',
                    'ti-hand-drag' => 'hand-drag',
                    'ti-flag' => 'flag',
                    'ti-flag-alt' => 'flag-alt',
                    'ti-flag-alt-2' => 'flag-alt-2',
                    'ti-eye' => 'eye',
                    'ti-import' => 'import',
                    'ti-export' => 'export',
                    'ti-cup' => 'cup',
                    'ti-crown' => 'crown',
                    'ti-comments' => 'comments',
                    'ti-comment' => 'comment',
                    'ti-comment-alt' => 'comment-alt',
                    'ti-thought' => 'thought',
                    'ti-clip' => 'clip',
                    'ti-check' => 'check',
                    'ti-check-box' => 'check-box',
                    'ti-camera' => 'camera',
                    'ti-announcement' => 'announcement',
                    'ti-brush' => 'brush',
                    'ti-brush-alt' => 'brush-alt',
                    'ti-palette' => 'palette',
                    'ti-briefcase' => 'briefcase',
                    'ti-bolt' => 'bolt',
                    'ti-bolt-alt' => 'bolt-alt',
                    'ti-blackboard' => 'blackboard',
                    'ti-bag' => 'bag',
                    'ti-world' => 'world',
                    'ti-wheelchair' => 'wheelchair',
                    'ti-car' => 'car',
                    'ti-truck' => 'truck',
                    'ti-timer' => 'timer',
                    'ti-ticket' => 'ticket',
                    'ti-thumb-up' => 'thumb-up',
                    'ti-thumb-down' => 'thumb-down',
                    'ti-stats-up' => 'stats-up',
                    'ti-stats-down' => 'stats-down',
                    'ti-shine' => 'shine',
                    'ti-shift-right' => 'shift-right',
                    'ti-shift-left' => 'shift-left',
                    'ti-shift-right-alt' => 'shift-right-alt',
                    'ti-shift-left-alt' => 'shift-left-alt',
                    'ti-shield' => 'shield',
                    'ti-notepad' => 'notepad',
                    'ti-server' => 'server',
                    'ti-pulse' => 'pulse',
                    'ti-printer' => 'printer',
                    'ti-power-off' => 'power-off',
                    'ti-plug' => 'plug',
                    'ti-pie-chart' => 'pie-chart',
                    'ti-panel' => 'panel',
                    'ti-package' => 'package',
                    'ti-music' => 'music',
                    'ti-music-alt' => 'music-alt',
                    'ti-mouse' => 'mouse',
                    'ti-mouse-alt' => 'mouse-alt',
                    'ti-money' => 'money',
                    'ti-microphone' => 'microphone',
                    'ti-menu' => 'menu',
                    'ti-menu-alt' => 'menu-alt',
                    'ti-map' => 'map',
                    'ti-map-alt' => 'map-alt',
                    'ti-location-pin' => 'location-pin',
                    'ti-light-bulb' => 'light-bulb',
                    'ti-info' => 'info',
                    'ti-infinite' => 'infinite',
                    'ti-id-badge' => 'id-badge',
                    'ti-hummer' => 'hummer',
                    'ti-home' => 'home',
                    'ti-help' => 'help',
                    'ti-headphone' => 'headphone',
                    'ti-harddrives' => 'harddrives',
                    'ti-harddrive' => 'harddrive',
                    'ti-gift' => 'gift',
                    'ti-game' => 'game',
                    'ti-filter' => 'filter',
                    'ti-files' => 'files',
                    'ti-file' => 'file',
                    'ti-zip' => 'zip',
                    'ti-folder' => 'folder',
                    'ti-envelope' => 'envelope',
                    'ti-dashboard' => 'dashboard',
                    'ti-cloud' => 'cloud',
                    'ti-cloud-up' => 'cloud-up',
                    'ti-cloud-down' => 'cloud-down',
                    'ti-clipboard' => 'clipboard',
                    'ti-calendar' => 'calendar',
                    'ti-book' => 'book',
                    'ti-bell' => 'bell',
                    'ti-basketball' => 'basketball',
                    'ti-bar-chart' => 'bar-chart',
                    'ti-bar-chart-alt' => 'bar-chart-alt',
                    'ti-archive' => 'archive',
                    'ti-anchor' => 'anchor',
                    'ti-alert' => 'alert',
                    'ti-alarm-clock' => 'alarm-clock',
                    'ti-agenda' => 'agenda',
                    'ti-write' => 'write',
                    'ti-wallet' => 'wallet',
                    'ti-video-clapper' => 'video-clapper',
                    'ti-video-camera' => 'video-camera',
                    'ti-vector' => 'vector',
                    'ti-support' => 'support',
                    'ti-stamp' => 'stamp',
                    'ti-slice' => 'slice',
                    'ti-shortcode' => 'shortcode',
                    'ti-receipt' => 'receipt',
                    'ti-pin2' => 'pin2',
                    'ti-pin-alt' => 'pin-alt',
                    'ti-pencil-alt2' => 'pencil-alt2',
                    'ti-eraser' => 'eraser',
                    'ti-more' => 'more',
                    'ti-more-alt' => 'more-alt',
                    'ti-microphone-alt' => 'microphone-alt',
                    'ti-magnet' => 'magnet',
                    'ti-line-double' => 'line-double',
                    'ti-line-dotted' => 'line-dotted',
                    'ti-line-dashed' => 'line-dashed',
                    'ti-ink-pen' => 'ink-pen',
                    'ti-info-alt' => 'info-alt',
                    'ti-help-alt' => 'help-alt',
                    'ti-headphone-alt' => 'headphone-alt',
                    'ti-gallery' => 'gallery',
                    'ti-face-smile' => 'face-smile',
                    'ti-face-sad' => 'face-sad',
                    'ti-credit-card' => 'credit-card',
                    'ti-comments-smiley' => 'comments-smiley',
                    'ti-time' => 'time',
                    'ti-share' => 'share',
                    'ti-share-alt' => 'share-alt',
                    'ti-rocket' => 'rocket',
                    'ti-new-window' => 'new-window',
                    'ti-rss' => 'rss',
                    'ti-rss-alt' => 'rss-alt',
                ];
            case 'control':
                return [
                    'ti-control-stop' => 'control-stop',
                    'ti-control-shuffle' => 'control-shuffle',
                    'ti-control-play' => 'control-play',
                    'ti-control-pause' => 'control-pause',
                    'ti-control-forward' => 'control-forward',
                    'ti-control-backward' => 'control-backward',
                    'ti-volume' => 'volume',
                    'ti-control-skip-forward' => 'control-skip-forward',
                    'ti-control-skip-backward' => 'control-skip-backward',
                    'ti-control-record' => 'control-record',
                    'ti-control-eject' => 'control-eject',
                ];


            case 'text-editor':
                return [
                    'ti-paragraph' => 'paragraph',
                    'ti-uppercase' => 'uppercase',
                    'ti-underline' => 'underline',
                    'ti-text' => 'text',
                    'ti-Italic' => 'Italic',
                    'ti-smallcap' => 'smallcap',
                    'ti-list' => 'list',
                    'ti-list-ol' => 'list-ol',
                    'ti-align-right' => 'align-right',
                    'ti-align-left' => 'align-left',
                    'ti-align-justify' => 'align-justify',
                    'ti-align-center' => 'align-center',
                    'ti-quote-right' => 'quote-right',
                    'ti-quote-left' => 'quote-left',
                ];
            case 'layout':
                return [
                    'ti-layout-width-full' => 'layout-width-full',
                    'ti-layout-width-default' => 'layout-width-default',
                    'ti-layout-width-default-alt' => 'layout-width-default-alt',
                    'ti-layout-tab' => 'layout-tab',
                    'ti-layout-tab-window' => 'layout-tab-window',
                    'ti-layout-tab-v' => 'layout-tab-v',
                    'ti-layout-tab-min' => 'layout-tab-min',
                    'ti-layout-slider' => 'layout-slider',
                    'ti-layout-slider-alt' => 'layout-slider-alt',
                    'ti-layout-sidebar-right' => 'layout-sidebar-right',
                    'ti-layout-sidebar-none' => 'layout-sidebar-none',
                    'ti-layout-sidebar-left' => 'layout-sidebar-left',
                    'ti-layout-placeholder' => 'layout-placeholder',
                    'ti-layout-menu' => 'layout-menu',
                    'ti-layout-menu-v' => 'layout-menu-v',
                    'ti-layout-menu-separated' => 'layout-menu-separated',
                    'ti-layout-menu-full' => 'layout-menu-full',
                    'ti-layout-media-right' => 'layout-media-right',
                    'ti-layout-media-right-alt' => 'layout-media-right-alt',
                    'ti-layout-media-overlay' => 'layout-media-overlay',
                    'ti-layout-media-overlay-alt' => 'layout-media-overlay-alt',
                    'ti-layout-media-overlay-alt-2' => 'layout-media-overlay-alt-2',
                    'ti-layout-media-left' => 'layout-media-left',
                    'ti-layout-media-left-alt' => 'layout-media-left-alt',
                    'ti-layout-media-center' => 'layout-media-center',
                    'ti-layout-media-center-alt' => 'layout-media-center-alt',
                    'ti-layout-list-thumb' => 'layout-list-thumb',
                    'ti-layout-list-thumb-alt' => 'layout-list-thumb-alt',
                    'ti-layout-list-post' => 'layout-list-post',
                    'ti-layout-list-large-image' => 'layout-list-large-image',
                    'ti-layout-line-solid' => 'layout-line-solid',
                    'ti-layout-grid4' => 'layout-grid4',
                    'ti-layout-grid3' => 'layout-grid3',
                    'ti-layout-grid2' => 'layout-grid2',
                    'ti-layout-grid2-thumb' => 'layout-grid2-thumb',
                    'ti-layout-cta-right' => 'layout-cta-right',
                    'ti-layout-cta-left' => 'layout-cta-left',
                    'ti-layout-cta-center' => 'layout-cta-center',
                    'ti-layout-cta-btn-right' => 'layout-cta-btn-right',
                    'ti-layout-cta-btn-left' => 'layout-cta-btn-left',
                    'ti-layout-column4' => 'layout-column4',
                    'ti-layout-column3' => 'layout-column3',
                    'ti-layout-column2' => 'layout-column2',
                    'ti-layout-accordion-separated' => 'layout-accordion-separated',
                    'ti-layout-accordion-merged' => 'layout-accordion-merged',
                    'ti-layout-accordion-list' => 'layout-accordion-list',
                    'ti-widgetized' => 'widgetized',
                    'ti-widget' => 'widget',
                    'ti-widget-alt' => 'widget-alt',
                    'ti-view-list' => 'view-list',
                    'ti-view-list-alt' => 'view-list-alt',
                    'ti-view-grid' => 'view-grid',
                    'ti-upload' => 'upload',
                    'ti-download' => 'download',
                    'ti-loop' => 'loop',
                    'ti-layout-sidebar-2' => 'layout-sidebar-2',
                    'ti-layout-grid4-alt' => 'layout-grid4-alt',
                    'ti-layout-grid3-alt' => 'layout-grid3-alt',
                    'ti-layout-grid2-alt' => 'layout-grid2-alt',
                    'ti-layout-column4-alt' => 'layout-column4-alt',
                    'ti-layout-column3-alt' => 'layout-column3-alt',
                    'ti-layout-column2-alt' => 'layout-column2-alt',
                ];
            case 'brand':
                return [
                    'ti-flickr' => 'flickr',
                    'ti-flickr-alt' => 'flickr-alt',
                    'ti-instagram' => 'instagram',
                    'ti-google' => 'google',
                    'ti-github' => 'github',
                    'ti-facebook' => 'facebook',
                    'ti-dropbox' => 'dropbox',
                    'ti-dropbox-alt' => 'dropbox-alt',
                    'ti-dribbble' => 'dribbble',
                    'ti-apple' => 'apple',
                    'ti-android' => 'android',
                    'ti-yahoo' => 'yahoo',
                    'ti-trello' => 'trello',
                    'ti-stack-overflow' => 'stack-overflow',
                    'ti-soundcloud' => 'soundcloud',
                    'ti-sharethis' => 'sharethis',
                    'ti-sharethis-alt' => 'sharethis-alt',
                    'ti-reddit' => 'reddit',
                    'ti-microsoft' => 'microsoft',
                    'ti-microsoft-alt' => 'microsoft-alt',
                    'ti-linux' => 'linux',
                    'ti-jsfiddle' => 'jsfiddle',
                    'ti-joomla' => 'joomla',
                    'ti-html5' => 'html5',
                    'ti-css3' => 'css3',
                    'ti-drupal' => 'drupal',
                    'ti-wordpress' => 'wordpress',
                    'ti-tumblr' => 'tumblr',
                    'ti-tumblr-alt' => 'tumblr-alt',
                    'ti-skype' => 'skype',
                    'ti-youtube' => 'youtube',
                    'ti-vimeo' => 'vimeo',
                    'ti-vimeo-alt' => 'vimeo-alt',
                    'ti-twitter' => 'twitter',
                    'ti-twitter-alt' => 'twitter-alt',
                    'ti-linkedin' => 'linkedin',
                    'ti-pinterest' => 'pinterest',
                    'ti-pinterest-alt' => 'pinterest-alt',
                    'ti-themify-logo' => 'themify-logo',
                    'ti-themify-favicon' => 'themify-favicon',
                    'ti-themify-favicon-alt' => 'themify-favicon-alt',
                ];


            default:
                return [];

        }

    }

}
