INSERT INTO `currencies` (`id`, `code`, `name`, `currency_name`, `symbol`)
VALUES (1, 'AWG', 'Arubin florin', 'florin', 'ƒ'),
       (2, 'AFN', 'Afghan Afghani', 'afghani', '؋'),
       (3, 'AOA', 'Angolan Kwanza', 'Kwanza', 'Kz'),
       (4, 'XCD', 'East Caribbean dollar', 'dollar', 'EC$'),
       (5, 'EUR', 'Euro', 'euro', '€'),
       (6, 'ALL', 'Albanian lek', 'lek', 'lek'),
       (7, 'AED', 'Emirati Dirham', 'dirham', '.د.ب'),
       (8, 'ARS', 'Argentine peso', 'peso', '$'),
       (9, 'AMD', 'Armenian dram', 'dram', '֏'),
       (10, 'USD', 'US Dollar', 'dollar', '$'),
       (11, 'AUD', 'Australian Dollar', 'dollar', '$'),
       (12, 'AZN', 'Azerbaijani manat', 'manat', 'ман'),
       (13, 'BIF', 'Burundian Franc', 'franc', 'FBu'),
       (14, 'XOF', 'CFA Franc', 'franc', 'CFA'),
       (15, 'BDT', 'Bangladeshi Taka', 'Taka', 'Tk'),
       (16, 'BGN', 'Bulgarian lev', 'lev', 'лв'),
       (17, 'BHD', 'Bahraini Dinar', 'dinar', '.د.ب or BD'),
       (18, 'BSD', 'Bahamian dollar', 'dollar', 'B$'),
       (19, 'BAM', 'Bosnian Convertible Marka', 'convertible marks', 'KM'),
       (20, 'BYR', 'Belarusian ruble', 'ruble', 'р'),
       (21, 'BZD', 'Belize dollar', 'dollar', 'BZ$'),
       (22, 'BMD', 'Bermudian dollar', 'dollar', '$'),
       (23, 'BOB', 'Bolivian Boliviano', 'boliviano', '$b'),
       (24, 'BRL', 'Brazilian real', 'real', 'R$'),
       (25, 'BBD', 'Barbadian dollar', 'dollar', '$'),
       (26, 'BND', 'Bruneian Dollar', 'dollar', '$'),
       (27, 'BTN', 'Bhutanese Ngultrum', 'Ngultrum', 'Nu.'),
       (28, 'INR', 'Indian Rupee', 'Rupee', '₹'),
       (29, 'BWP', 'Botswana Pula', 'Pula', 'P'),
       (30, 'CAD', 'Canadian Dollar', 'dollar', '$'),
       (31, 'CHF', 'Swiss Franc', 'franc', 'CHF'),
       (32, 'CLP', 'Chilean Peso', 'peso', '$'),
       (33, 'CNY', 'Yuan or chinese renminbi', 'yuan', '¥'),
       (34, 'NZD', 'New Zealand Dollar', 'dollar', '$'),
       (35, 'COP', 'Colombian peso', 'peso', '$'),
       (36, 'KMF', 'Comoran Franc', 'franc', 'CF'),
       (37, 'CVE', 'Cape Verdean Escudo', 'escudo', '$'),
       (38, 'CRC', 'Costa Rican colón', 'colón', '₡'),
       (39, 'CUC', 'Cuban convertible peso', 'peso', '$'),
       (40, 'CUP', 'Cuban peso', 'peso', '₱'),
       (41, 'ANG', 'Dutch Guilder', 'guilder', 'ƒ'),
       (42, 'KYD', 'Caymanian Dollar', 'dollar', '$'),
       (43, 'CZK', 'Czech koruna', 'koruna', 'Kč'),
       (44, 'DJF', 'Djiboutian Franc', 'franc', 'fdj'),
       (45, 'DKK', 'Danish krone', 'kroner', 'kr'),
       (46, 'DOP', 'Dominican peso', 'peso', '$'),
       (47, 'DZD', 'Algerian Dinar', 'dinar', 'جد'),
       (48, 'EGP', 'Egyptian Pound', 'pound', '£ '),
       (49, 'ERN', 'Eritrean nakfa', 'nafka', 'ናቕፋ'),
       (50, 'MAD', 'Moroccan Dirham', 'dirham', 'م.د.'),
       (51, 'MRO', 'Mauritanian Ouguiya', 'Ouguiya', 'UM'),
       (52, 'ETB', 'Ethiopian Birr', 'Birr', 'Br'),
       (53, 'FJD', 'Fijian dollar', 'dollar', '$'),
       (54, 'FKP', 'Falkland Island Pound', 'pound', '£'),
       (55, 'GBP', 'British Pound', 'pound', '£'),
       (56, 'GEL', 'Georgian lari', 'lari', 'ლ'),
       (57, 'GHS', 'Ghanaian Cedi', 'Cedi', 'GH¢'),
       (58, 'GIP', 'Gibraltar pound', 'pound', '£'),
       (59, 'GNF', 'Guinean Franc', 'franc', 'FG'),
       (60, 'GMD', 'Gambian dalasi', 'dalasi', 'D'),
       (61, 'GTQ', 'Guatemalan Quetzal', 'quetzales', 'Q'),
       (62, 'GYD', 'Guyanese dollar', 'dollar', '$'),
       (63, 'HKD', 'Hong Kong dollar', 'dollar', 'HK$'),
       (64, 'HNL', 'Honduran lempira', 'lempira', 'L'),
       (65, 'HRK', 'Croatian kuna', 'kuna', 'kn'),
       (66, 'HTG', 'Haitian gourde', 'gourde', 'G'),
       (67, 'HUF', 'Hungarian forint', 'forint', 'Ft'),
       (68, 'IDR', 'Indonesian Rupiah', 'Rupiah', 'Rp'),
       (69, 'IRR', 'Iranian Rial', 'rial', '﷼'),
       (70, 'IQD', 'Iraqi Dinar', 'dinar', 'ع.د'),
       (71, 'ISK', 'Icelandic Krona', 'krona', 'kr'),
       (72, 'ILS', 'Israeli Shekel', 'Shekel', '₪'),
       (73, 'JMD', 'Jamaican dollar', 'dollar', 'J$'),
       (74, 'JOD', 'Jordanian Dinar', 'Dinar', 'د.ا'),
       (75, 'JPY', 'Japanese yen', 'yen', '¥'),
       (76, 'KZT', 'Kazakhstani tenge', 'tenge', '₸'),
       (77, 'KES', 'Kenyan Shilling', 'Shilling', 'KSh'),
       (78, 'KGS', 'Kyrgyzstani som', 'som', 'лв'),
       (79, 'KHR', 'Cambodian Riel', 'riel', '៛'),
       (80, 'KRW', 'South Korean won', 'won', '₩'),
       (81, 'KWD', 'Kuwaiti Dinar', 'dinar', 'ك'),
       (82, 'LAK', 'Lao or Laotian Kip', 'Kip', '₭'),
       (83, 'LBP', 'Lebanese Pound', 'pound', 'ل.ل'),
       (84, 'LRD', 'Liberian Dollar', 'dollar', '$'),
       (85, 'LYD', 'Libyan Dinar', 'dinar', ' د.ل'),
       (86, 'LKR', 'Sri Lankan Rupee', 'Rupee', 'Rs'),
       (87, 'LSL', 'Lesotho loti', 'loti (maloti)', 'L or M'),
       (88, 'ZAR', 'South African Rand', 'Rand', 'R'),
       (89, 'MOP', 'Macau Pataca', 'pataca', 'MOP$'),
       (90, 'MDL', 'Moldovan Leu', 'Leu', 'L'),
       (91, 'MGA', 'Malagasy Ariary', 'Ariary', 'Ar'),
       (92, 'MVR', 'Maldivian Rufiyaa', 'Rufiyaa', 'rf'),
       (93, 'MXN', 'Mexico Peso', 'dollar', '$'),
       (94, 'MKD', 'Macedonian Denar', 'denar', 'ден'),
       (95, 'MMK', 'Burmese Kyat', 'Kyat', 'K'),
       (96, 'MNT', 'Mongolian Tughrik', 'Tughrik', '₮'),
       (97, 'MZN', 'Mozambican Metical', 'metical', 'MT'),
       (98, 'MUR', 'Mauritian rupee', 'rupee', 'Rs'),
       (99, 'MWK', 'Malawian Kwacha', 'Kwacha', 'MK'),
       (100, 'MYR', 'Malaysian Ringgit', 'Ringgit', 'RM'),
       (101, 'NAD', 'Namibian Dollar', 'dollar', '$'),
       (102, 'XPF', 'CFP Franc', 'franc', '₣'),
       (103, 'NGN', 'Nigerian Naira', 'Naira', '₦'),
       (104, 'NIO', 'Nicaraguan córdoba', 'córdoba', 'C$'),
       (105, 'NOK', 'Norwegian krone', 'Krone', 'kr'),
       (106, 'NPR', 'Nepalese Rupee', 'Rupee', 'Rs'),
       (107, 'OMR', 'Omani Rial', 'rial', 'ع.ر.'),
       (108, 'PKR', 'Pakistani Rupee', 'Rupee', 'Rs'),
       (109, 'PAB', 'Balboa panamérn', 'balboa', 'B/'),
       (110, 'PEN', 'Peruvian nuevo sol', 'nuevo sol', 'S/'),
       (111, 'PHP', 'Philippine Peso', 'Peso', '₱'),
       (112, 'PGK', 'Papua New Guinean Kina', 'Kina', 'K'),
       (113, 'PLN', 'Polish złoty', 'złoty', 'zł'),
       (114, 'KPW', 'North Korean won', 'won', '₩'),
       (115, 'PYG', 'Paraguayan guarani', 'guarani', '₲'),
       (116, 'QAR', 'Qatari Riyal', 'riyal', 'ق.ر '),
       (117, 'RON', 'Romanian leu', 'leu', 'lei'),
       (118, 'RUB', 'Russian Rouble', 'rouble', '₽'),
       (119, 'RWF', 'Rwandan franc', 'franc', 'FRw, RF, R₣'),
       (120, 'SAR', 'Saudi Arabian Riyal', 'riyal', 'ر.س'),
       (121, 'SDG', 'Sudanese Pound', 'pound', 'ج.س.'),
       (122, 'SGD', 'Singapore Dollar', 'dollar', '$'),
       (123, 'SBD', 'Solomon Islander Dollar', 'dollar', 'SI$'),
       (124, 'SLL', 'Sierra Leonean Leone', 'Leone', 'Le'),
       (125, 'SOS', 'Somali Shilling', 'shilling', 'S'),
       (126, 'RSD', 'Serbian Dinar', 'dinar', 'РСД'),
       (127, 'SSP', 'South Sudanese pound', 'pound', '£'),
       (128, 'SRD', 'Surinamese dollar', 'dollar', '$'),
       (129, 'SEK', 'Swedish krona', 'krona', 'kr'),
       (130, 'SZL', 'Swazi Lilangeni', 'Lilangeni or emalangeni', 'L or E'),
       (131, 'SCR', 'Seychellois Rupee', 'rupee', 'Rs'),
       (132, 'SYP', 'Syrian Pound', 'pound', '£'),
       (133, 'THB', 'Thai Baht', 'baht', '฿'),
       (134, 'TJS', 'Tajikistani somoni', 'somoni', 'ЅM'),
       (135, 'TMT', 'Turkmenistan manat', 'manat', 'T'),
       (136, 'TOP', 'Tongan Paanga', 'hau', 'T$'),
       (137, 'TTD', 'Trinidadian dollar', 'dollar', 'TT$'),
       (138, 'TND', 'Tunisian Dinar', 'dinar', 'DT'),
       (139, 'TRY', 'Turkish Lira', 'lira', '₺'),
       (140, 'TWD', 'Taiwan New Dollar', 'dollar', 'NT$'),
       (141, 'TZS', 'Tanzanian Shilling', 'Shilling', 'Sh'),
       (142, 'UGX', 'Ugandan Shilling', 'Shilling', 'USh'),
       (143, 'UAH', 'Ukrainian Hryvnia', 'Hryvnia', '₴'),
       (144, 'UYU', 'Uruguayan peso', 'peso', '$U'),
       (145, 'UZS', 'Uzbekistani som', 'som', 'лв'),
       (146, 'VEF', 'Venezuelan bolivar', 'bolívares fuertes', 'Bs'),
       (147, 'VND', 'Vietnamese Dong', 'dong', '₫'),
       (148, 'VUV', 'Ni-Vanuatu Vatu', 'vatu', 'VT'),
       (149, 'WST', 'Samoan Tālā', 'tālā', '$'),
       (150, 'YER', 'Yemeni Rial', 'rial', '﷼'),
       (151, 'ZMW', 'Zambian Kwacha', 'Kwacha', 'ZMK');
